# .github/workflows/deploy.yml
name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.FLEET_STG_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.FLEET_STG_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to cPanel Frontend Next.js App
        run: |
          ssh ${{ secrets.FLEET_STG_USER }}@${{ secrets.FLEET_STG_HOST }} << 'EOF'
            echo "ðŸš€ Starting deployment on cPanel..."
            
            # Navigate to your app directory
            cd /home/${{ secrets.FLEET_STG_USER }}/frontend-prod

            echo "ðŸŒ Activating Node.js virtual environment"

            source /home/${{ secrets.FLEET_STG_USER }}/nodevenv/frontend-prod/24/bin/activate

            echo "ðŸ“¦ Pulling latest code"
            git pull origin develop

            echo "ðŸ“¦ Installing production dependencies"
            npm ci --legacy-peer-deps

            echo "ðŸ›  Building the app"
            npm run build

            echo "ðŸ§© Restarting cPanel Node.js Application"
            source /home/${{ secrets.FLEET_STG_USER }}/nodevenv/frontend-prod/24/bin/activate
            cd /home/${{ secrets.FLEET_STG_USER }}/frontend-prod
            mkdir -p tmp
            touch tmp/restart.txt
            echo "âœ… Deployment completed successfully!"
          EOF
